Additional button for show proposal page
openpoke/decidim-module-reporting-proposals pull request #39
Opened 2023-01-23 23:31 UTC by antopalidi

fix #38 
<img width="830" alt="screen" src="https://user-images.githubusercontent.com/60363870/214175587-6faa7962-ad80-4b75-a404-09253231af6f.png">

2023-01-24 10:10 UTC, microstudi commented on app/overrides/decidim/proposals/proposals/show/add_additional_button.html.erb.deface
> +<%= render partial: "decidim/proposals/proposals/additional_button_for_show" %>
```suggestion
<%= render partial: "decidim/reporting_proposals/proposals/additional_button_for_show" %>
```
We should put this view in our own namespace

2023-01-24 11:50 UTC, microstudi requested changes
Also, I'd would like to remove the checkbox:
![image](https://user-images.githubusercontent.com/1401520/214284370-6fcd4d32-8458-49da-9ff1-9d3f78c58c47.png)

Let's show the button if there's text and link and just not show if there's not.

2023-01-24 20:33 UTC, antopalidi commented
> Also, I'd would like to remove the checkbox: ![image](https://user-images.githubusercontent.com/1401520/214284370-6fcd4d32-8458-49da-9ff1-9d3f78c58c47.png)
> 
> Let's show the button if there's text and link and just not show if there's not.

I found it unnecessary to create a checkbox for each custom button. So I left one for both buttons first. Now I added a second checkbox.

2023-01-25 14:09 UTC, microstudi approved these changes
thanks!

2023-01-25 14:09 UTC, merged